#ifndef __SPXCONFIG_H__
#define __SPXCONFIG_H__

#define CMAKE_BUILD_TYPE "Release"

#define SOPLEX_VERSION_MAJOR 6
#define SOPLEX_VERSION_MINOR 0
#define SOPLEX_VERSION_PATCH 2
#define SOPLEX_VERSION_SUB 0
#define SOPLEX_VERSION_API 11
/* #undef SOPLEX_WITH_BOOST */
#define SOPLEX_WITH_CPPMPF
/* #undef SOPLEX_WITH_FLOAT128 */
/* #undef SOPLEX_WITH_GMP */
/* #undef SOPLEX_WITH_MPFR */
/* #undef SOPLEX_WITH_PAPILO */
#define SOPLEX_WITH_ZLIB

#endif
